cc_binary(name = "query_count",
          srcs = ["query_count.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

# cc_binary(name = "query_click",
#           srcs = ["query_click.cc"],
#            deps = ["//base/common/BUILD:base",
#                    "//base/strings/BUILD:strings",
#                    "//base/encoding/BUILD:encoding",
#                    "//log_analysis/common/BUILD:log_common"
#                    ]
#          )

# cc_binary(name = "url_ref_count",
#           srcs = ["url_ref_count.cc"],
#            deps = ["//base/common/BUILD:base",
#                    "//base/strings/BUILD:strings",
#                    "//base/encoding/BUILD:encoding",
#                    "//log_analysis/common/BUILD:log_common"
#                    ]
#          )

# cc_binary(name = "parse_se.cc",
#           srcs = ["parse_se.cc"],
#            deps = ["//base/common/BUILD:base",
#                    "//base/strings/BUILD:strings",
#                    "//base/encoding/BUILD:encoding",
#                    "//web/html/utils/BUILD:utils",
#                    "//log_analysis/common/BUILD:log_common"
#                    ]
#         )

cc_binary(name = "url_query",
          srcs = ["url_query.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//web/html/utils/BUILD:utils",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )


