cc_binary(name = "search_r1",
          srcs = ["search_r1.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

cc_binary(name = "search_r2",
          srcs = ["search_r2.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

cc_binary(name = "search_combine",
          srcs = ["search_combine.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

cc_binary(name = "find_search_query",
          srcs = ["find_search_query.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

cc_binary(name = "search_plus",
          srcs = ["search_plus.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

