cc_binary(name = "mr_offline_site_stat_mapper",
          srcs = ["mr_offline_site_stat_mapper.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  ]
          )
cc_binary(name = "mr_offline_site_stat_reducer",
          srcs = ["mr_offline_site_stat_reducer.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  ]
          )
