cc_binary(name = "pv_r1",
          srcs = ["pv_r1.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

cc_binary(name = "pv_r2",
          srcs = ["pv_r2.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

cc_binary(name = "pv_plus",
          srcs = ["pv_plus.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//web/html/utils/BUILD:utils",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

cc_binary(name = "pv_combine",
          srcs = ["pv_combine.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//web/html/utils/BUILD:utils",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

