cc_binary(name = "mr_hub_page_dig_mapper",
          srcs = ["mr_hub_page_dig_mapper.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//crawler/api/BUILD:base",
                  ]
          )
cc_binary(name = "mr_hub_page_dig_reducer",
          srcs = ["mr_hub_page_dig_reducer.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  ]
          )
