cc_library(name = "exchange",
           srcs = ["task_data.cc",
                   "report_status.cc",
                   ],
           deps = ["//base/file/BUILD:file",
                   "//base/strings/BUILD:strings",
                   "//crawler/proto/BUILD:crawled_resource"
                   ],
           );
           
