cc_binary(name = "url_query",
          srcs = ["url_query.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//web/html/utils/BUILD:utils",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )
