cc_binary(name = "mr_domain_url_mapper",
          srcs = ["mr_domain_url_mapper.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//crawler/api/BUILD:base",
                  "//web/url/BUILD:url",
                  ]
          )
cc_binary(name = "mr_domain_url_reducer",
          srcs = ["mr_domain_url_reducer.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  ]
          )
