cc_binary(name = "query_count",
          srcs = ["query_count.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common",
                   ]
         )

cc_binary(name = "vertical_query_count",
          srcs = ["vertical_query_count.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common",
                   ]
         )
