cc_binary(name = "output_to_shard",
          srcs = ["output_to_shard.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  "//crawler/exchange/BUILD:exchange",
                  "//crawler/proto/BUILD:crawled_resource",
                  "//crawler/api/BUILD:base"
                  ]
          )

