cc_binary(name = "search_pv_userid",
          srcs = ["search_pv_userid.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//log_analysis/common/BUILD:log_common",
                  "//base/mapreduce/BUILD:mapreduce"
                  ]
          )


cc_binary(name = "search_pv_clk",
          srcs = ["search_pv_clk.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//log_analysis/common/BUILD:log_common",
                  "//base/mapreduce/BUILD:mapreduce"
                  ]
          )

cc_binary(name = "search_pv_clk_r2",
          srcs = ["search_pv_clk_r2.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//log_analysis/common/BUILD:log_common",
                  "//base/mapreduce/BUILD:mapreduce"
                  ]
          )

cc_binary(name = "to_train_data",
          srcs = ["to_train_data.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//log_analysis/common/BUILD:log_common",
                  "//base/mapreduce/BUILD:mapreduce"
                  ]
          )

cc_binary(name = "search_pv_query_r1",
          srcs = ["search_pv_query_r1.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//log_analysis/common/BUILD:log_common",
                  "//base/mapreduce/BUILD:mapreduce"
                  ]
          )

cc_binary(name = "search_pv_query_r2",
          srcs = ["search_pv_query_r2.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//log_analysis/common/BUILD:log_common",
                  "//base/mapreduce/BUILD:mapreduce"
                  ]
          )

cc_binary(name = "url_query_count.cc",
          srcs = ["url_query_count.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//log_analysis/common/BUILD:log_common",
                  "//base/mapreduce/BUILD:mapreduce"
                  ]
          )
