cc_binary(name = "schedule_to_fetcher_id",
          srcs = ["schedule_to_fetcher_id.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  "//crawler/exchange/BUILD:exchange"
                  ]
          )

cc_binary(name = "ip_stat",
          srcs = ["ip_stat.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  ]
          )

cc_binary(name = "dns_query_on_hadoop",
          srcs = ["dns_query_on_hadoop.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  "//crawler/exchange/BUILD:exchange",
                  "//crawler/util/BUILD:util"
                  ]
          )

# cc_binary(name = "dns_query_on_local",
#           srcs = ["dns_query_on_local.cc"],
#           deps = ["//base/common/BUILD:base",
#                   "//base/strings/BUILD:strings",
#                   "//base/mapreduce/BUILD:mapreduce",
#                   "//web/url/BUILD:url",
#                   "//crawler/exchange/BUILD:exchange",
#                   "//crawler/util/BUILD:util"
#                   ]
#           )

cc_binary(name = "url_to_ip",
          srcs = ["url_to_ip.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  "//crawler/exchange/BUILD:exchange",
                  "//crawler/util/BUILD:util",
                  "//crawler/proto/BUILD:crawled_resource"
                  ]
          )

cc_binary(name = "ip_host_url_stat",
          srcs = ["ip_host_url_stat.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  "//crawler/exchange/BUILD:exchange"
                  ]
          )

cc_binary(name = "ip_host_url_stat_report",
          srcs = ["ip_host_url_stat_report.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  "//crawler/exchange/BUILD:exchange"
                  ]
          )

cc_binary(name = "ip_url_split",
          srcs = ["ip_url_split.cc"],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//web/url/BUILD:url",
                  "//crawler/exchange/BUILD:exchange"
                  ]
          )
