cc_binary(name = "mr_stat_site_pv_mapper",
          srcs = ["mr_stat_site_pv_mapper.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//base/strings/BUILD:strings",
                  "//base/encoding/BUILD:encoding",
                  "//web/url/BUILD:url",
                  ]
          )

cc_binary(name = "mr_stat_site_pv_reducer",
          srcs = ["mr_stat_site_pv_reducer.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//base/strings/BUILD:strings",
                  ]
          )
