cc_binary(name = "md5_map",
          srcs = ["md5_map.cc"],
           deps = ["//base/common/BUILD:base",
                   "//base/strings/BUILD:strings",
                   "//base/encoding/BUILD:encoding",
                   "//log_analysis/common/BUILD:log_common"
                   ]
         )

# cc_binary(name = "convert",
#           srcs = ["convert.cc"],
#            deps = ["//base/common/BUILD:base",
#                    "//base/strings/BUILD:strings",
#                    "//base/encoding/BUILD:encoding",
#                    "//log_analysis/common/BUILD:log_common"
#                    ]
#          )
