cc_binary(name = "mr_link_merge_mapper",
          srcs = ["mr_link_merge_mapper.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//crawler/selector/BUILD:selector_util",
                  ]
          )
cc_binary(name = "mr_link_merge_reducer",
          srcs = ["mr_link_merge_reducer.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  ]
          )
