cc_binary(name = "mapper_compress_control",
          srcs = ["mapper_compress_control.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//base/hash_function/BUILD:hash_function",
                  "//crawler/proto/BUILD:crawled_resource",
                  "//web/url/BUILD:url",
                  ]
          )

cc_binary(name = "reducer_compress_control",
          srcs = ["reducer_compress_control.cc",],
          deps = ["//base/common/BUILD:base",
                  "//base/strings/BUILD:strings",
                  "//base/mapreduce/BUILD:mapreduce",
                  "//base/hash_function/BUILD:hash_function",
                  "//crawler/proto/BUILD:crawled_resource",
                  "//web/url/BUILD:url",
                  ]
          )
