
cc_binary(name = "host_stat",
          srcs = ["host_stat.cc",],
          deps = ["//base/strings/BUILD:strings",
                  "//crawler/fetcher2/BUILD:fetcher",
                  "//web/url/BUILD:url",
                  "//base/mapreduce/BUILD:mapreduce",
                  ],
          );

